# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_organizationalunittype_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalunittype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='companies.OrganizationalUnitType'),
        ),
    ]
