# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20160923_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='unit_type',
            field=models.ManyToManyField(related_name='unit', to='companies.OrganizationalUnitType'),
        ),
    ]
