# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20160923_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='unit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='companies.OrganizationalUnitType'),
            preserve_default=False,
        ),
    ]
